FROM apache/airflow:3.3.2-python3.12

USER airflow
RUN pip install --no-cache-dir pandas==2.3.1 duckdb==1.3.2 pandera==0.25.0 pyarrow==21.0.0 requests==2.32.4 PyYAML==6.0.2 psutil==7.0.0 psycopg2-binary==2.9.10

COPY --chown=airflow:root src /opt/airflow/src
COPY --chown=airflow:root configs /opt/airflow/configs
COPY --chown=airflow:root docker/airflow_dags /opt/airflow/dags
ENV PYTHONPATH=/opt/airflow/src
CMD ["python", "-c", "from climate_pipeline.orchestrators.airflow_dag import airflow_dag; print(airflow_dag)"]
